site_name: Kullanıcı Kılavuzu 

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: none
    navigation_depth: 3
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true


plugins:
    - search:
        lang: tr

markdown_extensions:
  - footnotes

nav:
  - Hiyerarşik Yapıyı Kullanarak Tarama Yapmak: 'Browser.md'
  - Hızlı Arama Yardımı: 'Quick-search.md'
  - Gelişmiş Arama Yardım: 'Advanced-search.md'
  - Postkoordinasyon: 'Postcoordination.md'